# Generated by Django 3.2.9 on 2021-12-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_ast_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.FloatField(max_length=100)),
                ('image_url', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
