# Generated by Django 3.2.9 on 2021-12-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_plan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='board',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='board',
            new_name='item',
        ),
    ]
